### PR TITLE
SPEED: check if there's only one match and say there's a utility of 0

### PR DESCRIPTION
**Pull request by kavigupta**
# Timing

## Default settings

Before: Individual times: [48.17, 50.05, 49.08, 50.38, 49.39]. Median: 49.39
After: Individual times: [39.9, 40.43, 40.44, 41.12, 39.75]. Median: 40.43

Time change: -18%

## allow_single_task=true

Apply this patch [test-with-single-task.txt](https://github.com/mlb2251/Stitch.jl/files/13823144/test-with-single-task.txt)

Before: Individual times: [33.59, 34.28, 34.67, 33.44, 33.33]. Median: 33.59
After: Individual times: [32.97, 33.28, 33.06, 33.2, 33.77]. Median: 33.2

Time change: -1%

# When it matters

The only way this is ever inaccurate is if somehow a single match actually compresses the sequence. This could happen in the case where you have compression that results entirely from argument reuse, e.g.,

```
(+ (+ 1 2 3) (+ 1 2 3) (+ 1 2 3) (+ 1 2 3) (+ 4 5 6) (+ 4 5 6) (+ 4 5 6) (+ 4 5 6))
```

being compressed to

```
fn_1 = (+ #0 #0 #0 #0 #1 #1 #1 #1)
(fn_1 (+ 1 2 3) (+ 4 5 6))
```

However, this is prevented by argument capture, so I guard the check with that flag. There is a test to ensure this doesn't break anything that I added previously: `data/basic/compression-from-absvar.json`

### CODE REVIEW

**Comment by mlb2251** [comment]
@kavigupta

hmm wait so there's this other flag `allow_single_task` that should prune any branches where an abstraction is only used for a single task (in our case, each program is a diff task so this is equivalent to just having a single match location).

https://github.com/mlb2251/Stitch.jl/blob/87ecd957903af63dd4c2f2904fb4a25e90546e82/src/search.jl#L122C10-L122C10

I left that turned on by default I think because sometime people who randomly wanna use stitch just pass in a single big program and want to know what abstractions it can come up with from that (I encountered that with a few people). Though given what a perf difference it is I dont love that, maybe its better to default it to off.

Regardless, for compress_imperative its set to default to off: https://github.com/mlb2251/Stitch.jl/blob/87ecd957903af63dd4c2f2904fb4a25e90546e82/src/search.jl#L540

Is that flag set to true or false in your timings? It seems to me like it should have a pretty equivalent effect, but I'm not sure.

**Comment by kavigupta** [comment]
@mlb2251 
It's set to off. Let me check what happens when I flip it on

**Comment by mlb2251** [comment]
Okay wait I feel like the more I think about it the more I think your optimization is good to have in addition to the other one:

**Comment by mlb2251** [comment]
Because "1 task/program that might have multiple matches" vs "1 match" are pretty different things and should be separate.

Even if users want to allow an abstraction that works for only one program/task, they still probably dont want abstractions that match at exactly one location.

Technically you can get some compression out of such an abstraction – either via the multiuse arguments as you point out, or if you weight the size of programs in your library lower than you weight the corpus itself (DC does the opposite of this btw, treating library expressions as 1.5x larger than program ones, and it's not clear why you'd want to do the opposite so this seems like likely a nonissue). However any abstraction that matches at a single location is not much of an abstraction at all haha, and I think it's really reasonable to not return those. Worth noting it explicitly somewhere – maybe just make a flag that disables this optimization but have it turned on by default.

So if you could just add a new `no_opt_*` flag to the config toggling this I'll merge!

**Pull request merged**
